CREATE DATABASE `kuryr` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE DATABASE `kuryr_01` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE `kuryr_02` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

