profile:
  env: "dev"

app:
  name: "kuryr"
  addr: "localhost:50501"
  group: "kuryr"
  timeout: 5000 # 单位：毫秒
  read_weight:  10
  write_weight: 100

etcd:
  endpoints:
    - "192.168.3.3:52379"
    - "192.168.3.3:52381"
    - "192.168.3.3:52383"
  username: "root"
  password: "<root_passwd>"
  dial_timeout: 5000            # 单位：毫秒
  tls:
    enabled: true
    cert_file: "etc/etcd-certs/client.pem"
    key_file: "etc/etcd-certs/client-key.pem"
    ca_file: "etc/etcd-certs/ca.pem"
    insecure_skip_verify: false

registry:
  lease_ttl: 30 # 单位：秒，这里和 etcd api 保持一直所以是秒单位

cache:
  defaultExpiration: 60000000000
  cleanupInterval: 60000000000

redis:
  addr: "192.168.3.3:6379"
  password: "<passwd>"

db:
  log_level: "info"
  slow_threshold: 200 # 慢查询阈值，单位：毫秒
  ignore_record_not_found_error: true
  base:
    # sslmode=disable 用于开发环境，线上一般推荐使用 sslmode=require / sslmode=verify-ca(更高安全性) / sslmode=verify-full (最高安全性)
    dsn: "postgres://jrmarcco:%3Cpasswd%3E@192.168.3.3:5432/kuryr?sslmode=disable&connect_timeout=1&statement_timeout=3000&idle_in_transaction_session_timeout=3000"
  sharding:
    - name: "kuryr_01"
      dsn: "postgres://jrmarcco:%3Cpasswd%3E@192.168.3.3:5432/kuryr_01?sslmode=disable&connect_timeout=1&statement_timeout=3000&idle_in_transaction_session_timeout=3000"
    - name: "kuryr_02"
      dsn: "postgres://jrmarcco:%3Cpasswd%3E@192.168.3.3:5432/kuryr_02?sslmode=disable&connect_timeout=1&statement_timeout=3000&idle_in_transaction_session_timeout=3000"

provider:
  encrypt_key: "<encrypt_key>"
