services:
  etcd-kuryr:
    image: bitnami/etcd:latest
    restart: unless-stopped
    ports:
      - "52379:2379"  # Client port
    environment:
      # Basic settings
      - ALLOW_NONE_AUTHENTICATION=no
      - ETCD_NAME=${ETCD_NAME}
      - ETCD_ROOT_PASSWORD=${ETCD_ROOT_PASSWORD}
      # Data directory
      - ETCD_DATA_DIR=/opt/bitnami/etcd/data
      # TLS settings
      - ETCD_CERT_FILE=/opt/bitnami/etcd/certs/server.pem
      - ETCD_KEY_FILE=/opt/bitnami/etcd/certs/server-key.pem
      - ETCD_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca.pem
      - ETCD_CLIENT_CERT_AUTH=true
      - ETCD_AUTO_TLS=false
      # 禁用非 TLS 连接的关键配置
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://0.0.0.0:2379
    volumes:
      - ./kuryr-data:/opt/bitnami/etcd/data
      - ./kuryr-certs:/opt/bitnami/etcd/certs:ro
